### ISSUE TITLE
hi 朋友 你这个vpn 上线过没 

### ISSUE THREAD

**Issue by alsojin0806** [alex-chan/SmartVPN#1]

**Comment by alex-chan** [comment]
1.0的上线了
你可以在appstore搜smartvpn
但现在服务器在维护，下午能好

wangjinwei0806 <notifications@github.com>于2017年5月19日 周五上午11:38写道：

**Comment by alsojin0806** [comment]
你这个不是ss吧

**Comment by alex-chan** [comment]
需要代理的时候走的是ss
wangjinwei0806 <notifications@github.com>于2017年5月19日 周五下午12:04写道：

**Comment by alex-chan** [comment]
正在做的是google直连

Alex Chan <czzsunset@gmail.com>于2017年5月19日 周五下午12:08写道：

**Comment by alsojin0806** [comment]
你这个还不错  公司的还是自己的项目 还提供服务，不知道速度怎么样

**Comment by alsojin0806** [comment]
也是基于NEKit, facebook messager 能正常连接不？

**Comment by alex-chan** [comment]
能，你可以试下，现在服务器好了
wangjinwei0806 <notifications@github.com>于2017年5月19日 周五下午12:14写道：

**Comment by alsojin0806** [comment]
好像 不行  一直提示正在连接

**Comment by alex-chan** [comment]
咦，好像是不行，以前还ok的

fb这个软件貌似使用了自己的底层协议

wangjinwei0806 <notifications@github.com>于2017年5月19日 周五下午2:35写道：

**Comment by alex-chan** [comment]
用浏览器访问google可行否
Alex Chan <czzsunset@gmail.com>于2017年5月19日 周五下午2:38写道：

**Comment by alsojin0806** [comment]
可以

**Comment by alsojin0806** [comment]
NEKit 本来就可以直接访问google 的

**Comment by alex-chan** [comment]
需要代理服务器吧
wangjinwei0806 <notifications@github.com>于2017年5月19日 周五下午2:43写道：

**Comment by alsojin0806** [comment]
这个必须的  朋友  你这个做了多久啊  mac 和ios 同步上线吗？

**Comment by alex-chan** [comment]
我现在做的是不需要服务器
随手做的，有时间就开发
mac端没有做好


wangjinwei0806 <notifications@github.com>于2017年5月19日 周五下午2:46写道：

**Comment by wangjinwei0806** [comment]
不错 啊 方便加QQ 聊不 我也过一款 我的QQ 21418925

**Comment by alex-chan** [comment]
可以，晚点下班后
有机会一起合作

wangjinwei0806 <notifications@github.com>于2017年5月19日 周五下午2:50写道：

**Comment by alsojin0806** [comment]
我的 mac 和ios  都上线了 可以讨论一下

**Comment by alex-chan** [comment]
上班聊q不方便
你给你你app链接？
wangjinwei0806 <notifications@github.com>于2017年5月19日 周五下午2:54写道：

**Comment by wangjinwei0806** [comment]
SsrConnect  这一款 你到app 搜索一下

**Comment by alsojin0806** [comment]
https://github.com/alex-chan/SmartVPN/blob/master/PacketTunnel/PacketTunnelProvider.swift#L163
你这里为啥要这样写

**Comment by alex-chan** [comment]
这是一个自定义DNS试验功能
